encrypting added

diff --git a/oimcrypt b/oimcrypt
--- a/oimcrypt
+++ b/oimcrypt
@@ -2,14 +2,14 @@
 
 set -o errexit
 
-if [ $# = 0 ]
-then
-  echo "ERROR - Syntax: $0 filename"
-  echo "    Lines in file must look like         username:pwd"
-  echo "    Using database table USR attributes  USR_LOGIN:USR_PASSWORD"
-  echo
-  exit 80
-fi
+# if [ $# = 0 ]
+# then
+#   echo "ERROR - Syntax: $0 filename"
+#   echo "    Lines in file must look like         username:pwd"
+#   echo "    Using database table USR attributes  USR_LOGIN:USR_PASSWORD"
+#   echo
+#   exit 80
+# fi
 
 . ./setenv.sh
 
@@ -20,21 +20,20 @@ cj="at.agoracon.oim.Crypto"
 if [ ! -f "classes/${cf}.class" ] || \
    [ "classes/${cf}.class" -ot "src/${cf}.java" ]
 then
-  echo "Compiling classes..."
+  echo "Compiling classes..." >&2
   [ -d classes ] || mkdir -p classes
   javac -d classes "src/${cf}.java"
-  echo "Compilation finished"
+  echo "Compilation finished" >&2
 fi
 
 # run
-echo "Starting program. Please be patient, Java is slow..."
-cat $1 | \
+echo "Starting program. Please be patient, Java is slow..." >&2
 java -DDOMAIN_HOME=${DOMAIN_HOME} \
   -DOIM_HOME=${ORACLE_HOME}/server \
   -Doracle.security.jps.config=${DOMAIN_HOME}/config/fmwconfig/jps-config-jse.xml \
   -DXL.HomeDir=/${DOMAIN_HOME}/config/fmwconfig \
   -DJAVA_HOME=${JAVA_HOME} \
   -DkeyStoreFileName=.xldatabasekey \
-  ${cj}
+  ${cj} $*
 
 # vi:ft=sh:
